services:
  dashboard:
    container_name: dashboard-dev
    image: hummingbot/dashboard:latest
    ports:
      - "8501:8501"
    environment:
      - AUTH_SYSTEM_ENABLED=False
      - BACKEND_API_HOST=backend-api-dev
      - BACKEND_API_PORT=8000
      - BACKEND_API_USERNAME=admin
      - BACKEND_API_PASSWORD=admin
      - DEBUG=True
      - STREAMLIT_SERVER_RUN_ON_SAVE=true
    volumes:
      - ./credentials.yml:/home/dashboard/credentials.yml
      - ./dashboard:/home/dashboard
    networks:
      - emqx-bridge-dev

  backend-api:
    container_name: backend-api-dev
    image: hummingbot/backend-api:latest
    ports:
      - "8000:8000"
    volumes:
      - ./bots:/backend-api/bots
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./backend-api:/backend-api
    env_file:
      - .env
    environment:
      - BROKER_HOST=emqx
      - BROKER_PORT=1883
      - BROKER_TYPE=emqx
      - USERNAME=admin
      - PASSWORD=admin
      - DEBUG=True
      - PYTHONPATH=/backend-api
    networks:
      - emqx-bridge-dev

  emqx:
    container_name: hummingbot-broker-dev
    image: emqx:5
    restart: unless-stopped
    environment:
      - EMQX_NAME=emqx
      - EMQX_HOST=node1.emqx.local
      - EMQX_CLUSTER__DISCOVERY_STRATEGY=static
      - EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.local]
      - EMQX_LOADED_PLUGINS="emqx_recon,emqx_retainer,emqx_management,emqx_dashboard"
    volumes:
      - emqx-data-dev:/opt/emqx/data
      - emqx-log-dev:/opt/emqx/log
      - emqx-etc-dev:/opt/emqx/etc
    ports:
      - "1883:1883"
      - "8883:8883"
      - "8083:8083"
      - "8084:8084"
      - "8081:8081"
      - "18083:18083"
      - "61613:61613"
    networks:
      emqx-bridge-dev:
        aliases:
          - node1.emqx.local
    healthcheck:
      test: [ "CMD", "/opt/emqx/bin/emqx_ctl", "status" ]
      interval: 5s
      timeout: 25s
      retries: 5

networks:
  emqx-bridge-dev:
    driver: bridge

volumes:
  emqx-data-dev: {}
  emqx-log-dev: {}
  emqx-etc-dev: {}
